export enum componentsEnum {
  PROGRESSBAR = "Progress Bar",
  OTPINPUT = "OTP Input",
  FILEEXPLORER = "File Explorer",
  NESTEDCOMMENTS = "Nested Comments",
  TICTACTOE = "Tic-Tac-Toe",
  ADVANCETODO = "Advance To Do List",
  MULTISTEPPERFORM = "Multi-Stepper",
  GRIDLIGHTS = "Grid Lights",
  EMICLACULATOR = "EMI Calculator",
  COUNTDOWNTIMER = "Countdown Timer",
  PAGINATION = "Pagination",
  SEARCH = "Autocomplete Search",
  DRAGNDROP = "Drag N Drop",
  CHATAPP = "Chat App",
}
